on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:


name: generate completions

jobs:
  completions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: rustup completion
        run: rustup completions zsh rustup > ./src/_rustup
      - name: cargo completion
        run: rustup completions zsh cargo > ./src/_cargo
      - name: just completion
        run: cargo install just && just --completions zsh > ./src/_just

      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.3
      - name: poetry completion
        run: poetry completions zsh > ./src/_poetry

      - name: Install kind
        uses: helm/kind-action@v1.2.0
        with:
          wait: 0s
      - name: kind completion
        run: kind completion zsh > ./src/_kind

      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: deno completion
        run: deno completions zsh > ./src/_deno

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update completions

